services:
  web:
    # FIXME: compose.prod.yamlのようにbuild時にもdockerfileを指定して良さそう
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  db:
    image: postgres:16.3
    volumes:
      # NOTE: volumesに関する記述を変えることで
      #       environmentに設定した値が反映されるようになった
      #       以前は全て postgres だったので初期設定だったのか？
      # TODO: 調べてブログに書く
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=emoemo_dev_user
      - POSTGRES_PASSWORD=emoemo_dev_pass
      - POSTGRES_DB=emoemo_dev
volumes:
  postgres_data:
