version: '3'

services:
  web:
    # NOTE: 修正前の書き方とはDockerfileを指定するのが違うだけ、という理解で合っているかな？
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/emoemo/web/static
      - media_volume:/emoemo/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # environment: があるとenv_file: が反映されないようだった
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/emoemo/web/static
      - media_volume:/emoemo/web/media
    ports:
      - "1337:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
