version: '3'

services:
  db:
    image: postgres:16.3
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/emoemo
      - static_volume:/emoemo/static
      - media_volume:/emoemo/media
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - static_volume:/emoemo/static
      - media_volume:/emoemo/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
