version: '3'

services:
  db:
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # environment: があるとenv_file: が反映されないようだった
    env_file:
      - ./.env.prod.db

  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/emoemo
      - static_volume:/emoemo/static
      - media_volume:/emoemo/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - static_volume:/emoemo/static
      - media_volume:/emoemo/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
